# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 978defd9d01052b5c96b6178086e8f38eb96c13d955b4a5a7bf186001c88af57b16aa0bd0ff31aa5b90909bbc3a002f0282aeebb40dd532975a015c4d5faa003

test:
  secret_key_base: 33d79f7f3bf02763ce970c8dcccbf1e3d37380a0d8157e7c7b4f5e40cb85ded7c1cfadbe437b08e82fcdaec420e893265aa9358a94e1adc6ac940a4e6f1e5b33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
